# when using the default proxy server port
# local_backend: true

backend:
  name: github
  repo: edonv/edonv.github.io
  branch: master
  # use_graphql: true
  # preview_context: my-provider/deployment

# This line should *not* be indented
media_folder: "images/uploads"
# public_folder defaults to media_folder with a leading "/"
# public_folder: "/images"

collections:
  - name: "works" # Used in routes, e.g., /admin/collections/works
    label: "Works" # Used in the UI
    folder: "_works" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      # - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date Range", name: "date-range", widget: "string", default: "April 2016 &ndash; May 2017" }
      - { label: "Show Carousel", name: "carousel", widget: "boolean" }
  - name: "pages" # Used in routes, e.g., /admin/collections/works
    label: "Pages" # Used in the UI
    files:
      - label: "About"
        name: "about"
        file: "pages/about.md"
        fields: # The fields for each document, usually in front matter
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body ID", name: "bodyid", widget: "hidden", default: "about" }
          - { label: "Permalink", name: "permalink", widget: "string", default: "/about.html" }

# Client ID: Ov23liR6Wu7zX9KgmcMH
# Client Secret: c12c9bd035bd804a2615504ad9318d8bbb3a2a94